### PR TITLE
bump to standard 5

### PR DESCRIPTION
**Pull request by ngoldman**
just some reformatting to pass standard 5+ and a couple readability improvements

### CODE REVIEW

**Comment by ngoldman** [comment]
noticed errors aren't standard here, as in

```
task.callback({ code: 400, error: 'Trouble parsing the CSV data' }, null)
```

at https://github.com/koopjs/koop-agol/pull/64/files#diff-2c02d67f20cb34e38b68a7584305888fR419

is it worth me doing a pass on that @dmfenton?

I'd do the same as in featureservice -- `new Error(msg)` + any extra properties like `code` tacked on.

**Comment by dmfenton** [comment]
Yep that would be very helpful. Pgcache really needs it as well. I was planning to do that to make some things easier on #63

**Comment by ngoldman** [comment]
@dmfenton guessing you mean #62? #63 is about bumping esri-leaflet version.

**Comment by ngoldman** [comment]
I will do that in another PR.

**Comment by dmfenton** [comment]
yeah #62

**Comment by ngoldman** [comment]
:grin:

**Pull request merged**
