### PR TITLE
drop failed resources after 30 minutes

### LINKED ISSUE #28: Koop should be self healing
Under construction :construction: 

Koop should drop it's own cache when it encounters certain failure conditions:

- 202 with no change in count for x iterations
- 202 with no change in generating progress in x iterations
- any error where the cache has failed to generate but server did not return a 500 response

Others?

### PR DESCRIPTION
**Pull request by dmfenton**
This PR fixes a critical bug where datasets in a failed state are never expired automatically. Now they will expire after a 30 minute period.

Resolves #28

### CODE REVIEW

**Comment by dmfenton** [comment]
ping @koopjs/dev

**Comment by jgravois** [comment]
i can QA this one now

**Comment by jgravois** [comment]
all tests passing after i laid down one more commit to appease the `standard gods`.  
should i merge as is or do you want me to rebase it first?

**Comment by dmfenton** [comment]
merge away good sir

**Pull request merged**
